# Generated by Django 4.0.4 on 2022-04-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='news-3.jpg', upload_to=''),
        ),
    ]
