# Generated by Django 4.0.4 on 2022-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser_main', '0002_post_post_id_alter_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='news-3.jpg', null=True, upload_to=''),
        ),
    ]
